// ISO 3166-1 countries with currency codes and India FTA status
// FTA = Free Trade Agreement in force with India as of 2025
// (SAFTA, ASEAN, Japan, South Korea, UAE CEPA, Australia ECTA, Sri Lanka, Mauritius, Singapore CECA)
export const countries = [
  { code: 'AF', code3: 'AFG', name: 'Afghanistan', currencyCode: 'AFN', ftaWithIndia: true },
  { code: 'AL', code3: 'ALB', name: 'Albania', currencyCode: 'ALL', ftaWithIndia: false },
  { code: 'DZ', code3: 'DZA', name: 'Algeria', currencyCode: 'DZD', ftaWithIndia: false },
  { code: 'AO', code3: 'AGO', name: 'Angola', currencyCode: 'AOA', ftaWithIndia: false },
  { code: 'AR', code3: 'ARG', name: 'Argentina', currencyCode: 'ARS', ftaWithIndia: false },
  { code: 'AU', code3: 'AUS', name: 'Australia', currencyCode: 'AUD', ftaWithIndia: true },
  { code: 'AT', code3: 'AUT', name: 'Austria', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'AZ', code3: 'AZE', name: 'Azerbaijan', currencyCode: 'AZN', ftaWithIndia: false },
  { code: 'BH', code3: 'BHR', name: 'Bahrain', currencyCode: 'BHD', ftaWithIndia: false },
  { code: 'BD', code3: 'BGD', name: 'Bangladesh', currencyCode: 'BDT', ftaWithIndia: true },
  { code: 'BY', code3: 'BLR', name: 'Belarus', currencyCode: 'BYN', ftaWithIndia: false },
  { code: 'BE', code3: 'BEL', name: 'Belgium', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'BZ', code3: 'BLZ', name: 'Belize', currencyCode: 'BZD', ftaWithIndia: false },
  { code: 'BJ', code3: 'BEN', name: 'Benin', currencyCode: 'XOF', ftaWithIndia: false },
  { code: 'BT', code3: 'BTN', name: 'Bhutan', currencyCode: 'BTN', ftaWithIndia: true },
  { code: 'BO', code3: 'BOL', name: 'Bolivia', currencyCode: 'BOB', ftaWithIndia: false },
  { code: 'BA', code3: 'BIH', name: 'Bosnia and Herzegovina', currencyCode: 'BAM', ftaWithIndia: false },
  { code: 'BW', code3: 'BWA', name: 'Botswana', currencyCode: 'BWP', ftaWithIndia: false },
  { code: 'BR', code3: 'BRA', name: 'Brazil', currencyCode: 'BRL', ftaWithIndia: false },
  { code: 'BN', code3: 'BRN', name: 'Brunei', currencyCode: 'BND', ftaWithIndia: true },
  { code: 'BG', code3: 'BGR', name: 'Bulgaria', currencyCode: 'BGN', ftaWithIndia: false },
  { code: 'BF', code3: 'BFA', name: 'Burkina Faso', currencyCode: 'XOF', ftaWithIndia: false },
  { code: 'MM', code3: 'MMR', name: 'Myanmar', currencyCode: 'MMK', ftaWithIndia: true },
  { code: 'BI', code3: 'BDI', name: 'Burundi', currencyCode: 'BIF', ftaWithIndia: false },
  { code: 'KH', code3: 'KHM', name: 'Cambodia', currencyCode: 'KHR', ftaWithIndia: true },
  { code: 'CM', code3: 'CMR', name: 'Cameroon', currencyCode: 'XAF', ftaWithIndia: false },
  { code: 'CA', code3: 'CAN', name: 'Canada', currencyCode: 'CAD', ftaWithIndia: false },
  { code: 'CV', code3: 'CPV', name: 'Cape Verde', currencyCode: 'CVE', ftaWithIndia: false },
  { code: 'CF', code3: 'CAF', name: 'Central African Republic', currencyCode: 'XAF', ftaWithIndia: false },
  { code: 'TD', code3: 'TCD', name: 'Chad', currencyCode: 'XAF', ftaWithIndia: false },
  { code: 'CL', code3: 'CHL', name: 'Chile', currencyCode: 'CLP', ftaWithIndia: false },
  { code: 'CN', code3: 'CHN', name: 'China', currencyCode: 'CNY', ftaWithIndia: false },
  { code: 'CO', code3: 'COL', name: 'Colombia', currencyCode: 'COP', ftaWithIndia: false },
  { code: 'KM', code3: 'COM', name: 'Comoros', currencyCode: 'KMF', ftaWithIndia: false },
  { code: 'CD', code3: 'COD', name: 'Congo (DRC)', currencyCode: 'CDF', ftaWithIndia: false },
  { code: 'CG', code3: 'COG', name: 'Congo (Republic)', currencyCode: 'XAF', ftaWithIndia: false },
  { code: 'CR', code3: 'CRI', name: 'Costa Rica', currencyCode: 'CRC', ftaWithIndia: false },
  { code: 'HR', code3: 'HRV', name: 'Croatia', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'CU', code3: 'CUB', name: 'Cuba', currencyCode: 'CUP', ftaWithIndia: false },
  { code: 'CY', code3: 'CYP', name: 'Cyprus', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'CZ', code3: 'CZE', name: 'Czech Republic', currencyCode: 'CZK', ftaWithIndia: false },
  { code: 'DK', code3: 'DNK', name: 'Denmark', currencyCode: 'DKK', ftaWithIndia: false },
  { code: 'DJ', code3: 'DJI', name: 'Djibouti', currencyCode: 'DJF', ftaWithIndia: false },
  { code: 'EC', code3: 'ECU', name: 'Ecuador', currencyCode: 'USD', ftaWithIndia: false },
  { code: 'EG', code3: 'EGY', name: 'Egypt', currencyCode: 'EGP', ftaWithIndia: false },
  { code: 'SV', code3: 'SLV', name: 'El Salvador', currencyCode: 'USD', ftaWithIndia: false },
  { code: 'GQ', code3: 'GNQ', name: 'Equatorial Guinea', currencyCode: 'XAF', ftaWithIndia: false },
  { code: 'ER', code3: 'ERI', name: 'Eritrea', currencyCode: 'ERN', ftaWithIndia: false },
  { code: 'EE', code3: 'EST', name: 'Estonia', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'ET', code3: 'ETH', name: 'Ethiopia', currencyCode: 'ETB', ftaWithIndia: false },
  { code: 'FJ', code3: 'FJI', name: 'Fiji', currencyCode: 'FJD', ftaWithIndia: false },
  { code: 'FI', code3: 'FIN', name: 'Finland', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'FR', code3: 'FRA', name: 'France', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'GA', code3: 'GAB', name: 'Gabon', currencyCode: 'XAF', ftaWithIndia: false },
  { code: 'GM', code3: 'GMB', name: 'Gambia', currencyCode: 'GMD', ftaWithIndia: false },
  { code: 'GE', code3: 'GEO', name: 'Georgia', currencyCode: 'GEL', ftaWithIndia: false },
  { code: 'DE', code3: 'DEU', name: 'Germany', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'GH', code3: 'GHA', name: 'Ghana', currencyCode: 'GHS', ftaWithIndia: false },
  { code: 'GR', code3: 'GRC', name: 'Greece', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'GT', code3: 'GTM', name: 'Guatemala', currencyCode: 'GTQ', ftaWithIndia: false },
  { code: 'GN', code3: 'GIN', name: 'Guinea', currencyCode: 'GNF', ftaWithIndia: false },
  { code: 'GW', code3: 'GNB', name: 'Guinea-Bissau', currencyCode: 'XOF', ftaWithIndia: false },
  { code: 'GY', code3: 'GUY', name: 'Guyana', currencyCode: 'GYD', ftaWithIndia: false },
  { code: 'HT', code3: 'HTI', name: 'Haiti', currencyCode: 'HTG', ftaWithIndia: false },
  { code: 'HN', code3: 'HND', name: 'Honduras', currencyCode: 'HNL', ftaWithIndia: false },
  { code: 'HK', code3: 'HKG', name: 'Hong Kong', currencyCode: 'HKD', ftaWithIndia: false },
  { code: 'HU', code3: 'HUN', name: 'Hungary', currencyCode: 'HUF', ftaWithIndia: false },
  { code: 'IS', code3: 'ISL', name: 'Iceland', currencyCode: 'ISK', ftaWithIndia: false },
  { code: 'IN', code3: 'IND', name: 'India', currencyCode: 'INR', ftaWithIndia: false },
  { code: 'ID', code3: 'IDN', name: 'Indonesia', currencyCode: 'IDR', ftaWithIndia: true },
  { code: 'IR', code3: 'IRN', name: 'Iran', currencyCode: 'IRR', ftaWithIndia: false },
  { code: 'IQ', code3: 'IRQ', name: 'Iraq', currencyCode: 'IQD', ftaWithIndia: false },
  { code: 'IE', code3: 'IRL', name: 'Ireland', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'IL', code3: 'ISR', name: 'Israel', currencyCode: 'ILS', ftaWithIndia: false },
  { code: 'IT', code3: 'ITA', name: 'Italy', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'JM', code3: 'JAM', name: 'Jamaica', currencyCode: 'JMD', ftaWithIndia: false },
  { code: 'JP', code3: 'JPN', name: 'Japan', currencyCode: 'JPY', ftaWithIndia: true },
  { code: 'JO', code3: 'JOR', name: 'Jordan', currencyCode: 'JOD', ftaWithIndia: false },
  { code: 'KZ', code3: 'KAZ', name: 'Kazakhstan', currencyCode: 'KZT', ftaWithIndia: false },
  { code: 'KE', code3: 'KEN', name: 'Kenya', currencyCode: 'KES', ftaWithIndia: false },
  { code: 'KP', code3: 'PRK', name: 'North Korea', currencyCode: 'KPW', ftaWithIndia: false },
  { code: 'KR', code3: 'KOR', name: 'South Korea', currencyCode: 'KRW', ftaWithIndia: true },
  { code: 'KW', code3: 'KWT', name: 'Kuwait', currencyCode: 'KWD', ftaWithIndia: false },
  { code: 'KG', code3: 'KGZ', name: 'Kyrgyzstan', currencyCode: 'KGS', ftaWithIndia: false },
  { code: 'LA', code3: 'LAO', name: 'Laos', currencyCode: 'LAK', ftaWithIndia: true },
  { code: 'LV', code3: 'LVA', name: 'Latvia', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'LB', code3: 'LBN', name: 'Lebanon', currencyCode: 'LBP', ftaWithIndia: false },
  { code: 'LS', code3: 'LSO', name: 'Lesotho', currencyCode: 'LSL', ftaWithIndia: false },
  { code: 'LR', code3: 'LBR', name: 'Liberia', currencyCode: 'LRD', ftaWithIndia: false },
  { code: 'LY', code3: 'LBY', name: 'Libya', currencyCode: 'LYD', ftaWithIndia: false },
  { code: 'LT', code3: 'LTU', name: 'Lithuania', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'LU', code3: 'LUX', name: 'Luxembourg', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'MG', code3: 'MDG', name: 'Madagascar', currencyCode: 'MGA', ftaWithIndia: false },
  { code: 'MW', code3: 'MWI', name: 'Malawi', currencyCode: 'MWK', ftaWithIndia: false },
  { code: 'MY', code3: 'MYS', name: 'Malaysia', currencyCode: 'MYR', ftaWithIndia: true },
  { code: 'MV', code3: 'MDV', name: 'Maldives', currencyCode: 'MVR', ftaWithIndia: true },
  { code: 'ML', code3: 'MLI', name: 'Mali', currencyCode: 'XOF', ftaWithIndia: false },
  { code: 'MT', code3: 'MLT', name: 'Malta', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'MR', code3: 'MRT', name: 'Mauritania', currencyCode: 'MRU', ftaWithIndia: false },
  { code: 'MU', code3: 'MUS', name: 'Mauritius', currencyCode: 'MUR', ftaWithIndia: true },
  { code: 'MX', code3: 'MEX', name: 'Mexico', currencyCode: 'MXN', ftaWithIndia: false },
  { code: 'MD', code3: 'MDA', name: 'Moldova', currencyCode: 'MDL', ftaWithIndia: false },
  { code: 'MN', code3: 'MNG', name: 'Mongolia', currencyCode: 'MNT', ftaWithIndia: false },
  { code: 'ME', code3: 'MNE', name: 'Montenegro', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'MA', code3: 'MAR', name: 'Morocco', currencyCode: 'MAD', ftaWithIndia: false },
  { code: 'MZ', code3: 'MOZ', name: 'Mozambique', currencyCode: 'MZN', ftaWithIndia: false },
  { code: 'NA', code3: 'NAM', name: 'Namibia', currencyCode: 'NAD', ftaWithIndia: false },
  { code: 'NP', code3: 'NPL', name: 'Nepal', currencyCode: 'NPR', ftaWithIndia: true },
  { code: 'NL', code3: 'NLD', name: 'Netherlands', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'NZ', code3: 'NZL', name: 'New Zealand', currencyCode: 'NZD', ftaWithIndia: false },
  { code: 'NI', code3: 'NIC', name: 'Nicaragua', currencyCode: 'NIO', ftaWithIndia: false },
  { code: 'NE', code3: 'NER', name: 'Niger', currencyCode: 'XOF', ftaWithIndia: false },
  { code: 'NG', code3: 'NGA', name: 'Nigeria', currencyCode: 'NGN', ftaWithIndia: false },
  { code: 'NO', code3: 'NOR', name: 'Norway', currencyCode: 'NOK', ftaWithIndia: false },
  { code: 'OM', code3: 'OMN', name: 'Oman', currencyCode: 'OMR', ftaWithIndia: false },
  { code: 'PK', code3: 'PAK', name: 'Pakistan', currencyCode: 'PKR', ftaWithIndia: true },
  { code: 'PA', code3: 'PAN', name: 'Panama', currencyCode: 'PAB', ftaWithIndia: false },
  { code: 'PG', code3: 'PNG', name: 'Papua New Guinea', currencyCode: 'PGK', ftaWithIndia: false },
  { code: 'PY', code3: 'PRY', name: 'Paraguay', currencyCode: 'PYG', ftaWithIndia: false },
  { code: 'PE', code3: 'PER', name: 'Peru', currencyCode: 'PEN', ftaWithIndia: false },
  { code: 'PH', code3: 'PHL', name: 'Philippines', currencyCode: 'PHP', ftaWithIndia: true },
  { code: 'PL', code3: 'POL', name: 'Poland', currencyCode: 'PLN', ftaWithIndia: false },
  { code: 'PT', code3: 'PRT', name: 'Portugal', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'QA', code3: 'QAT', name: 'Qatar', currencyCode: 'QAR', ftaWithIndia: false },
  { code: 'RO', code3: 'ROU', name: 'Romania', currencyCode: 'RON', ftaWithIndia: false },
  { code: 'RU', code3: 'RUS', name: 'Russia', currencyCode: 'RUB', ftaWithIndia: false },
  { code: 'RW', code3: 'RWA', name: 'Rwanda', currencyCode: 'RWF', ftaWithIndia: false },
  { code: 'SA', code3: 'SAU', name: 'Saudi Arabia', currencyCode: 'SAR', ftaWithIndia: false },
  { code: 'SN', code3: 'SEN', name: 'Senegal', currencyCode: 'XOF', ftaWithIndia: false },
  { code: 'RS', code3: 'SRB', name: 'Serbia', currencyCode: 'RSD', ftaWithIndia: false },
  { code: 'SL', code3: 'SLE', name: 'Sierra Leone', currencyCode: 'SLL', ftaWithIndia: false },
  { code: 'SG', code3: 'SGP', name: 'Singapore', currencyCode: 'SGD', ftaWithIndia: true },
  { code: 'SK', code3: 'SVK', name: 'Slovakia', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'SI', code3: 'SVN', name: 'Slovenia', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'SO', code3: 'SOM', name: 'Somalia', currencyCode: 'SOS', ftaWithIndia: false },
  { code: 'ZA', code3: 'ZAF', name: 'South Africa', currencyCode: 'ZAR', ftaWithIndia: false },
  { code: 'SS', code3: 'SSD', name: 'South Sudan', currencyCode: 'SSP', ftaWithIndia: false },
  { code: 'ES', code3: 'ESP', name: 'Spain', currencyCode: 'EUR', ftaWithIndia: false },
  { code: 'LK', code3: 'LKA', name: 'Sri Lanka', currencyCode: 'LKR', ftaWithIndia: true },
  { code: 'SD', code3: 'SDN', name: 'Sudan', currencyCode: 'SDG', ftaWithIndia: false },
  { code: 'SR', code3: 'SUR', name: 'Suriname', currencyCode: 'SRD', ftaWithIndia: false },
  { code: 'SE', code3: 'SWE', name: 'Sweden', currencyCode: 'SEK', ftaWithIndia: false },
  { code: 'CH', code3: 'CHE', name: 'Switzerland', currencyCode: 'CHF', ftaWithIndia: false },
  { code: 'SY', code3: 'SYR', name: 'Syria', currencyCode: 'SYP', ftaWithIndia: false },
  { code: 'TW', code3: 'TWN', name: 'Taiwan', currencyCode: 'TWD', ftaWithIndia: false },
  { code: 'TJ', code3: 'TJK', name: 'Tajikistan', currencyCode: 'TJS', ftaWithIndia: false },
  { code: 'TZ', code3: 'TZA', name: 'Tanzania', currencyCode: 'TZS', ftaWithIndia: false },
  { code: 'TH', code3: 'THA', name: 'Thailand', currencyCode: 'THB', ftaWithIndia: true },
  { code: 'TL', code3: 'TLS', name: 'Timor-Leste', currencyCode: 'USD', ftaWithIndia: false },
  { code: 'TG', code3: 'TGO', name: 'Togo', currencyCode: 'XOF', ftaWithIndia: false },
  { code: 'TT', code3: 'TTO', name: 'Trinidad and Tobago', currencyCode: 'TTD', ftaWithIndia: false },
  { code: 'TN', code3: 'TUN', name: 'Tunisia', currencyCode: 'TND', ftaWithIndia: false },
  { code: 'TR', code3: 'TUR', name: 'Turkey', currencyCode: 'TRY', ftaWithIndia: false },
  { code: 'TM', code3: 'TKM', name: 'Turkmenistan', currencyCode: 'TMT', ftaWithIndia: false },
  { code: 'UG', code3: 'UGA', name: 'Uganda', currencyCode: 'UGX', ftaWithIndia: false },
  { code: 'UA', code3: 'UKR', name: 'Ukraine', currencyCode: 'UAH', ftaWithIndia: false },
  { code: 'AE', code3: 'ARE', name: 'United Arab Emirates', currencyCode: 'AED', ftaWithIndia: true },
  { code: 'GB', code3: 'GBR', name: 'United Kingdom', currencyCode: 'GBP', ftaWithIndia: false },
  { code: 'US', code3: 'USA', name: 'United States', currencyCode: 'USD', ftaWithIndia: false },
  { code: 'UY', code3: 'URY', name: 'Uruguay', currencyCode: 'UYU', ftaWithIndia: false },
  { code: 'UZ', code3: 'UZB', name: 'Uzbekistan', currencyCode: 'UZS', ftaWithIndia: false },
  { code: 'VE', code3: 'VEN', name: 'Venezuela', currencyCode: 'VES', ftaWithIndia: false },
  { code: 'VN', code3: 'VNM', name: 'Vietnam', currencyCode: 'VND', ftaWithIndia: true },
  { code: 'YE', code3: 'YEM', name: 'Yemen', currencyCode: 'YER', ftaWithIndia: false },
  { code: 'ZM', code3: 'ZMB', name: 'Zambia', currencyCode: 'ZMW', ftaWithIndia: false },
  { code: 'ZW', code3: 'ZWE', name: 'Zimbabwe', currencyCode: 'ZWL', ftaWithIndia: false },
];