export const incoterms = [
  {
    code: 'EXW',
    name: 'Ex Works',
    riskTransferPoint: "Seller's premises",
    costDescription: 'Buyer bears all costs from seller\'s factory/warehouse. Seller has minimum obligation.',
    applicableModes: 'ALL',
  },
  {
    code: 'FCA',
    name: 'Free Carrier',
    riskTransferPoint: 'Named place of delivery (seller\'s premises or carrier)',
    costDescription: 'Seller delivers goods to named carrier/place. Risk transfers at that point. Suitable for containerized cargo.',
    applicableModes: 'ALL',
  },
  {
    code: 'CPT',
    name: 'Carriage Paid To',
    riskTransferPoint: 'When goods handed to first carrier',
    costDescription: 'Seller pays freight to named destination. Risk transfers at first carrier. Buyer arranges insurance.',
    applicableModes: 'ALL',
  },
  {
    code: 'CIP',
    name: 'Carriage and Insurance Paid To',
    riskTransferPoint: 'When goods handed to first carrier',
    costDescription: 'Seller pays freight and insurance (ICC A minimum) to named destination. Risk transfers at first carrier.',
    applicableModes: 'ALL',
  },
  {
    code: 'DAP',
    name: 'Delivered at Place',
    riskTransferPoint: 'Named destination, ready for unloading',
    costDescription: 'Seller bears all costs and risks to named place, ready for unloading. Buyer handles import customs and duties.',
    applicableModes: 'ALL',
  },
  {
    code: 'DPU',
    name: 'Delivered at Place Unloaded',
    riskTransferPoint: 'Named destination, after unloading',
    costDescription: 'Seller bears all costs and risks including unloading at destination. Buyer handles import customs.',
    applicableModes: 'ALL',
  },
  {
    code: 'DDP',
    name: 'Delivered Duty Paid',
    riskTransferPoint: 'Named destination, ready for unloading',
    costDescription: 'Seller bears all costs including import duties and taxes. Maximum obligation for seller.',
    applicableModes: 'ALL',
  },
  {
    code: 'FAS',
    name: 'Free Alongside Ship',
    riskTransferPoint: 'Alongside vessel at port of shipment',
    costDescription: 'Seller delivers goods alongside the vessel. Buyer bears loading costs and all subsequent costs.',
    applicableModes: 'SEA_ONLY',
  },
  {
    code: 'FOB',
    name: 'Free On Board',
    riskTransferPoint: 'On board the vessel at port of shipment',
    costDescription: 'Seller delivers on board the vessel. Risk transfers when goods cross the ship\'s rail. Most common for Indian exports.',
    applicableModes: 'SEA_ONLY',
  },
  {
    code: 'CFR',
    name: 'Cost and Freight',
    riskTransferPoint: 'On board vessel at port of shipment',
    costDescription: 'Seller pays freight to destination port. Risk transfers at port of shipment. Buyer arranges insurance.',
    applicableModes: 'SEA_ONLY',
  },
  {
    code: 'CIF',
    name: 'Cost, Insurance and Freight',
    riskTransferPoint: 'On board vessel at port of shipment',
    costDescription: 'Seller pays freight and insurance (ICC C minimum) to destination port. Risk transfers at port of shipment.',
    applicableModes: 'SEA_ONLY',
  },
];