export const uoms = [
  { code: 'PCS', name: 'Pieces' },
  { code: 'KG', name: 'Kilograms' },
  { code: 'GM', name: 'Grams' },
  { code: 'MT', name: 'Metric Tonnes' },
  { code: 'LTR', name: 'Litres' },
  { code: 'ML', name: 'Millilitres' },
  { code: 'CBM', name: 'Cubic Metres' },
  { code: 'SET', name: 'Sets' },
  { code: 'DOZ', name: 'Dozens' },
  { code: 'BOX', name: 'Boxes' },
  { code: 'CTN', name: 'Cartons' },
  { code: 'PAIR', name: 'Pairs' },
  { code: 'SQM', name: 'Square Metres' },
  { code: 'RM', name: 'Running Metres' },
  { code: 'BAG', name: 'Bags' },
  { code: 'BTL', name: 'Bottles' },
  { code: 'DRUM', name: 'Drums' },
  { code: 'PKT', name: 'Packets' },
  { code: 'ROLL', name: 'Rolls' },
  { code: 'UNIT', name: 'Units' },
];